import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "../components/Navbar/Navbar";
import CountDownBanner from "../components/CountDownBanner/CountDownBanner";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navMenuItems = [
  { name: "خانه", path: "/" },
  { name: "درباره ما", path: "/about" },
  { name: "تماس با ما", path: "/contact" },
];

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CountDownBanner />
        <Navbar items={navMenuItems} />
        {children}
      </body>
    </html>
  );
}
